services:
  web:
    image: docker.io/corbettzhang/bitpongofront:latest
    build: .
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    networks:
      - bitpongo-net

networks:
  bitpongo-net:
    external: true
