services:
  web:
    image: docker.io/corbettzhang/zhitoubaofront:latest
    build: .
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    networks:
      - zhitoubao-net

networks:
  zhitoubao-net:
    external: true
